# Generated by Django 6.0.3 on 2026-04-10 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobility', '0002_application_review'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={},
        ),
        migrations.AlterField(
            model_name='application',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='mobility.university'),
        ),
    ]
